remote_theme: pmarsceill/just-the-docs

title: SpecBind Docs

# Aux links for the upper right navigation
aux_links:
  "SpecBind on GitHub":
    - "//github.com/SpecBind/specbind"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SpecBind/specbind" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately